"""initial schema

Revision ID: 5160189e9fea
Revises:
Create Date: 2026-03-25 16:54:52.613284

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "global_settings",
        sa.Column("key", sa.String(length=255), nullable=False),
        sa.Column("value", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "hosts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("ip", sa.String(length=45), nullable=False),
        sa.Column("hostname", sa.String(length=255), nullable=True),
        sa.Column("is_pingable", sa.Boolean(), nullable=True),
        sa.Column("mac_address", sa.String(length=17), nullable=True),
        sa.Column("mac_vendor", sa.String(length=255), nullable=True),
        sa.Column("first_seen_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("user_comment", sa.Text(), nullable=True),
        sa.Column("seen_by_networks", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_hosts_ip"), "hosts", ["ip"], unique=True)
    op.create_table(
        "nse_scripts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("categories", sa.JSON(), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=True),
        sa.Column("type", sa.String(length=20), nullable=False),
        sa.Column("cloned_from", sa.String(length=200), nullable=True),
        sa.Column("author", sa.String(length=200), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "nse_templates",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("nse_scripts", sa.JSON(), nullable=False),
        sa.Column(
            "severity",
            sa.Enum("critical", "high", "medium", "info", name="nsetemplateseverity"),
            nullable=True,
        ),
        sa.Column("platform", sa.String(length=50), nullable=False),
        sa.Column("type", sa.Enum("builtin", "custom", name="nsetemplatetype"), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("script_args", sa.JSON(), nullable=True),
        sa.Column("category", sa.String(length=50), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "scanners",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("api_key_hash", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("location", sa.String(length=255), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(), nullable=True),
        sa.Column("scanner_version", sa.String(length=50), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "role",
            sa.Enum("admin", "operator", "analyst", "viewer", name="userrole"),
            nullable=False,
        ),
        sa.Column(
            "theme_preference",
            sa.Enum("light", "dark", "system", name="themepreference"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "global_open_ports",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("ip", sa.String(length=45), nullable=False),
        sa.Column("port", sa.Integer(), nullable=False),
        sa.Column("protocol", sa.String(length=10), nullable=False),
        sa.Column("banner", sa.Text(), nullable=True),
        sa.Column("service_guess", sa.String(length=100), nullable=True),
        sa.Column("mac_address", sa.String(length=17), nullable=True),
        sa.Column("mac_vendor", sa.String(length=255), nullable=True),
        sa.Column("first_seen_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("seen_by_networks", sa.JSON(), nullable=False),
        sa.Column("user_comment", sa.Text(), nullable=True),
        sa.Column("host_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["host_id"],
            ["hosts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ip", "port", "protocol", name="uq_global_open_ports_ip_port_protocol"),
    )
    op.create_index(
        op.f("ix_global_open_ports_host_id"), "global_open_ports", ["host_id"], unique=False
    )
    op.create_index(op.f("ix_global_open_ports_ip"), "global_open_ports", ["ip"], unique=False)
    op.create_index(
        "ix_global_open_ports_ip_port", "global_open_ports", ["ip", "port"], unique=False
    )
    op.create_index(op.f("ix_global_open_ports_port"), "global_open_ports", ["port"], unique=False)
    op.create_table(
        "global_port_rules",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("ip", sa.String(length=45), nullable=True),
        sa.Column("port", sa.String(length=20), nullable=False),
        sa.Column(
            "rule_type", sa.Enum("accepted", "critical", name="globalruletype"), nullable=False
        ),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_global_port_rules_created_by"), "global_port_rules", ["created_by"], unique=False
    )
    op.create_index(op.f("ix_global_port_rules_ip"), "global_port_rules", ["ip"], unique=False)
    op.create_table(
        "networks",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("cidr", sa.String(length=43), nullable=False),
        sa.Column("port_spec", sa.String(length=1000), nullable=False),
        sa.Column("scanner_id", sa.Integer(), nullable=False),
        sa.Column("scan_schedule", sa.String(length=100), nullable=True),
        sa.Column("scan_rate", sa.Integer(), nullable=True),
        sa.Column("scan_timeout", sa.Integer(), server_default="3600", nullable=True),
        sa.Column("port_timeout", sa.Integer(), server_default="1500", nullable=True),
        sa.Column("scanner_type", sa.String(length=20), server_default="masscan", nullable=False),
        sa.Column("scan_protocol", sa.String(length=10), server_default="tcp", nullable=False),
        sa.Column("alert_config", sa.JSON(), nullable=True),
        sa.Column(
            "nse_profile_id",
            sa.Integer(),
            nullable=True,
            comment="Default NSE profile for scheduled scans when scanner_type is nse",
        ),
        sa.Column("host_discovery_enabled", sa.Boolean(), server_default="1", nullable=False),
        sa.Column("scan_schedule_enabled", sa.Boolean(), server_default="1", nullable=False),
        sa.Column("phases", sa.JSON(), nullable=True, comment="Multi-phase scan pipeline config"),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["nse_profile_id"], ["nse_templates.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["scanner_id"],
            ["scanners.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_networks_nse_profile_id"), "networks", ["nse_profile_id"], unique=False
    )
    op.create_index(op.f("ix_networks_scanner_id"), "networks", ["scanner_id"], unique=False)
    op.create_table(
        "alert_rules",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("network_id", sa.Integer(), nullable=True),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column("rule_type", sa.Enum("accepted", "critical", name="ruletype"), nullable=False),
        sa.Column("match_criteria", sa.JSON(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("enabled", sa.Boolean(), server_default="1", nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["network_id"],
            ["networks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_alert_rules_created_by"), "alert_rules", ["created_by"], unique=False)
    op.create_index(op.f("ix_alert_rules_network_id"), "alert_rules", ["network_id"], unique=False)
    op.create_index(op.f("ix_alert_rules_source"), "alert_rules", ["source"], unique=False)
    op.create_table(
        "host_discovery_scans",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("network_id", sa.Integer(), nullable=False),
        sa.Column("scanner_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("planned", "running", "completed", "failed", name="hostdiscoveryscanstatus"),
            nullable=False,
        ),
        sa.Column(
            "trigger_type",
            sa.Enum("manual", "scheduled", name="hostdiscoverytriggertype"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("hosts_discovered", sa.Integer(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["network_id"],
            ["networks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["scanner_id"],
            ["scanners.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_host_discovery_scans_network_id"),
        "host_discovery_scans",
        ["network_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_host_discovery_scans_scanner_id"),
        "host_discovery_scans",
        ["scanner_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_host_discovery_scans_status"), "host_discovery_scans", ["status"], unique=False
    )
    op.create_table(
        "port_rules",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("network_id", sa.Integer(), nullable=False),
        sa.Column("ip", sa.String(length=45), nullable=True),
        sa.Column("port", sa.String(length=20), nullable=False),
        sa.Column("rule_type", sa.Enum("accepted", "critical", name="ruletype"), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["network_id"],
            ["networks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_port_rules_ip"), "port_rules", ["ip"], unique=False)
    op.create_index(op.f("ix_port_rules_network_id"), "port_rules", ["network_id"], unique=False)
    op.create_table(
        "scans",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("network_id", sa.Integer(), nullable=False),
        sa.Column("scanner_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("planned", "running", "completed", "failed", "cancelled", name="scanstatus"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(), nullable=True),
        sa.Column("cancelled_by", sa.Integer(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("progress_percent", sa.Float(), nullable=True),
        sa.Column("progress_message", sa.Text(), nullable=True),
        sa.Column("actual_rate", sa.Float(), nullable=True),
        sa.Column(
            "trigger_type", sa.Enum("manual", "scheduled", name="triggertype"), nullable=False
        ),
        sa.Column("hidden", sa.Boolean(), server_default="0", nullable=False),
        sa.Column(
            "target_ip",
            sa.Text(),
            nullable=True,
            comment="Target IP for single-host scan; NULL for full network scan",
        ),
        sa.Column(
            "nse_template_id",
            sa.Integer(),
            nullable=True,
            comment="NSE template used for this scan; NULL for non-NSE scans",
        ),
        sa.ForeignKeyConstraint(["cancelled_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["network_id"],
            ["networks.id"],
        ),
        sa.ForeignKeyConstraint(["nse_template_id"], ["nse_templates.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["scanner_id"],
            ["scanners.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_scans_hidden"), "scans", ["hidden"], unique=False)
    op.create_index(op.f("ix_scans_network_id"), "scans", ["network_id"], unique=False)
    op.create_index(op.f("ix_scans_nse_template_id"), "scans", ["nse_template_id"], unique=False)
    op.create_index(op.f("ix_scans_scanner_id"), "scans", ["scanner_id"], unique=False)
    op.create_index(op.f("ix_scans_status"), "scans", ["status"], unique=False)
    op.create_table(
        "alerts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("scan_id", sa.Integer(), nullable=True),
        sa.Column("network_id", sa.Integer(), nullable=True),
        sa.Column("global_open_port_id", sa.Integer(), nullable=True),
        sa.Column(
            "alert_type",
            sa.Enum(
                "new_port",
                "not_allowed",
                "blocked",
                "ssh_insecure_auth",
                "ssh_weak_cipher",
                "ssh_weak_kex",
                "ssh_outdated_version",
                "ssh_config_regression",
                "nse_vulnerability",
                "nse_cve_detected",
                name="alerttype",
            ),
            nullable=False,
        ),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column("ip", sa.String(length=45), nullable=False),
        sa.Column("port", sa.Integer(), nullable=True),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("dismissed", sa.Boolean(), nullable=False),
        sa.Column("dismiss_reason", sa.Text(), nullable=True),
        sa.Column("assigned_to_user_id", sa.Integer(), nullable=True),
        sa.Column(
            "resolution_status",
            sa.Enum("open", "in_progress", "resolved", "fix_planned", name="resolutionstatus"),
            nullable=False,
        ),
        sa.Column("severity_override", sa.String(length=20), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["assigned_to_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["global_open_port_id"],
            ["global_open_ports.id"],
        ),
        sa.ForeignKeyConstraint(
            ["network_id"],
            ["networks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["scan_id"],
            ["scans.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_alerts_assigned_to_user_id"), "alerts", ["assigned_to_user_id"], unique=False
    )
    op.create_index(
        op.f("ix_alerts_global_open_port_id"), "alerts", ["global_open_port_id"], unique=False
    )
    op.create_index(op.f("ix_alerts_ip"), "alerts", ["ip"], unique=False)
    op.create_index(op.f("ix_alerts_network_id"), "alerts", ["network_id"], unique=False)
    op.create_index(op.f("ix_alerts_port"), "alerts", ["port"], unique=False)
    op.create_index(op.f("ix_alerts_scan_id"), "alerts", ["scan_id"], unique=False)
    op.create_index(op.f("ix_alerts_source"), "alerts", ["source"], unique=False)
    op.create_table(
        "nse_results",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("scan_id", sa.Integer(), nullable=False),
        sa.Column("ip", sa.String(length=45), nullable=False),
        sa.Column("port", sa.Integer(), nullable=False),
        sa.Column("protocol", sa.String(length=10), nullable=False),
        sa.Column("script_name", sa.String(length=200), nullable=False),
        sa.Column("script_output", sa.Text(), nullable=False),
        sa.Column("cve_ids", sa.JSON(), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("template_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["scan_id"], ["scans.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["template_id"], ["nse_templates.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_nse_results_ip"), "nse_results", ["ip"], unique=False)
    op.create_index(op.f("ix_nse_results_scan_id"), "nse_results", ["scan_id"], unique=False)
    op.create_index(
        op.f("ix_nse_results_script_name"), "nse_results", ["script_name"], unique=False
    )
    op.create_index(
        op.f("ix_nse_results_template_id"), "nse_results", ["template_id"], unique=False
    )
    op.create_table(
        "open_ports",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("scan_id", sa.Integer(), nullable=False),
        sa.Column("ip", sa.String(length=45), nullable=False),
        sa.Column("port", sa.Integer(), nullable=False),
        sa.Column("protocol", sa.String(length=10), nullable=False),
        sa.Column("ttl", sa.Integer(), nullable=True),
        sa.Column("banner", sa.Text(), nullable=True),
        sa.Column("service_guess", sa.String(length=100), nullable=True),
        sa.Column("mac_address", sa.String(length=17), nullable=True),
        sa.Column("mac_vendor", sa.String(length=255), nullable=True),
        sa.Column("first_seen_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["scan_id"],
            ["scans.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_open_ports_ip"), "open_ports", ["ip"], unique=False)
    op.create_index(op.f("ix_open_ports_port"), "open_ports", ["port"], unique=False)
    op.create_index(op.f("ix_open_ports_scan_id"), "open_ports", ["scan_id"], unique=False)
    op.create_table(
        "scan_logs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("scan_id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("level", sa.Enum("info", "warning", "error", name="loglevel"), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["scan_id"],
            ["scans.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_scan_logs_scan_id"), "scan_logs", ["scan_id"], unique=False)
    op.create_table(
        "ssh_scan_results",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("scan_id", sa.Integer(), nullable=False),
        sa.Column("host_ip", sa.String(length=45), nullable=False),
        sa.Column("port", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("publickey_enabled", sa.Boolean(), nullable=False),
        sa.Column("password_enabled", sa.Boolean(), nullable=False),
        sa.Column("keyboard_interactive_enabled", sa.Boolean(), nullable=False),
        sa.Column("ssh_version", sa.String(length=100), nullable=True),
        sa.Column("protocol_version", sa.String(length=20), nullable=True),
        sa.Column("server_banner", sa.Text(), nullable=True),
        sa.Column("supported_ciphers", sa.JSON(), nullable=True),
        sa.Column("kex_algorithms", sa.JSON(), nullable=True),
        sa.Column("host_key_types", sa.JSON(), nullable=True),
        sa.Column("mac_algorithms", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["scan_id"], ["scans.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ssh_scan_results_host_ip"), "ssh_scan_results", ["host_ip"], unique=False
    )
    op.create_index(
        op.f("ix_ssh_scan_results_scan_id"), "ssh_scan_results", ["scan_id"], unique=False
    )
    op.create_table(
        "alert_comments",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("alert_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["alert_id"], ["alerts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_alert_comments_alert_id"), "alert_comments", ["alert_id"], unique=False
    )
    op.create_index(op.f("ix_alert_comments_user_id"), "alert_comments", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_alert_comments_user_id"), table_name="alert_comments")
    op.drop_index(op.f("ix_alert_comments_alert_id"), table_name="alert_comments")
    op.drop_table("alert_comments")
    op.drop_index(op.f("ix_ssh_scan_results_scan_id"), table_name="ssh_scan_results")
    op.drop_index(op.f("ix_ssh_scan_results_host_ip"), table_name="ssh_scan_results")
    op.drop_table("ssh_scan_results")
    op.drop_index(op.f("ix_scan_logs_scan_id"), table_name="scan_logs")
    op.drop_table("scan_logs")
    op.drop_index(op.f("ix_open_ports_scan_id"), table_name="open_ports")
    op.drop_index(op.f("ix_open_ports_port"), table_name="open_ports")
    op.drop_index(op.f("ix_open_ports_ip"), table_name="open_ports")
    op.drop_table("open_ports")
    op.drop_index(op.f("ix_nse_results_template_id"), table_name="nse_results")
    op.drop_index(op.f("ix_nse_results_script_name"), table_name="nse_results")
    op.drop_index(op.f("ix_nse_results_scan_id"), table_name="nse_results")
    op.drop_index(op.f("ix_nse_results_ip"), table_name="nse_results")
    op.drop_table("nse_results")
    op.drop_index(op.f("ix_alerts_source"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_scan_id"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_port"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_network_id"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_ip"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_global_open_port_id"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_assigned_to_user_id"), table_name="alerts")
    op.drop_table("alerts")
    op.drop_index(op.f("ix_scans_status"), table_name="scans")
    op.drop_index(op.f("ix_scans_scanner_id"), table_name="scans")
    op.drop_index(op.f("ix_scans_nse_template_id"), table_name="scans")
    op.drop_index(op.f("ix_scans_network_id"), table_name="scans")
    op.drop_index(op.f("ix_scans_hidden"), table_name="scans")
    op.drop_table("scans")
    op.drop_index(op.f("ix_port_rules_network_id"), table_name="port_rules")
    op.drop_index(op.f("ix_port_rules_ip"), table_name="port_rules")
    op.drop_table("port_rules")
    op.drop_index(op.f("ix_host_discovery_scans_status"), table_name="host_discovery_scans")
    op.drop_index(op.f("ix_host_discovery_scans_scanner_id"), table_name="host_discovery_scans")
    op.drop_index(op.f("ix_host_discovery_scans_network_id"), table_name="host_discovery_scans")
    op.drop_table("host_discovery_scans")
    op.drop_index(op.f("ix_alert_rules_source"), table_name="alert_rules")
    op.drop_index(op.f("ix_alert_rules_network_id"), table_name="alert_rules")
    op.drop_index(op.f("ix_alert_rules_created_by"), table_name="alert_rules")
    op.drop_table("alert_rules")
    op.drop_index(op.f("ix_networks_scanner_id"), table_name="networks")
    op.drop_index(op.f("ix_networks_nse_profile_id"), table_name="networks")
    op.drop_table("networks")
    op.drop_index(op.f("ix_global_port_rules_ip"), table_name="global_port_rules")
    op.drop_index(op.f("ix_global_port_rules_created_by"), table_name="global_port_rules")
    op.drop_table("global_port_rules")
    op.drop_index(op.f("ix_global_open_ports_port"), table_name="global_open_ports")
    op.drop_index("ix_global_open_ports_ip_port", table_name="global_open_ports")
    op.drop_index(op.f("ix_global_open_ports_ip"), table_name="global_open_ports")
    op.drop_index(op.f("ix_global_open_ports_host_id"), table_name="global_open_ports")
    op.drop_table("global_open_ports")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_table("scanners")
    op.drop_table("nse_templates")
    op.drop_table("nse_scripts")
    op.drop_index(op.f("ix_hosts_ip"), table_name="hosts")
    op.drop_table("hosts")
    op.drop_table("global_settings")
    # ### end Alembic commands ###
