/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedTrendsRouteImport } from './routes/_authenticated/trends'
import { Route as AuthenticatedAlertRulesRouteImport } from './routes/_authenticated/alert-rules'
import { Route as AuthenticatedScansIndexRouteImport } from './routes/_authenticated/scans/index'
import { Route as AuthenticatedScannersIndexRouteImport } from './routes/_authenticated/scanners/index'
import { Route as AuthenticatedNetworksIndexRouteImport } from './routes/_authenticated/networks/index'
import { Route as AuthenticatedHostsIndexRouteImport } from './routes/_authenticated/hosts/index'
import { Route as AuthenticatedAlertsIndexRouteImport } from './routes/_authenticated/alerts/index'
import { Route as AuthenticatedScansScanIdRouteImport } from './routes/_authenticated/scans/$scanId'
import { Route as AuthenticatedScannersScannerIdRouteImport } from './routes/_authenticated/scanners/$scannerId'
import { Route as AuthenticatedNseResultsRouteImport } from './routes/_authenticated/nse/results'
import { Route as AuthenticatedNseProfilesRouteImport } from './routes/_authenticated/nse/profiles'
import { Route as AuthenticatedNseLibraryRouteImport } from './routes/_authenticated/nse/library'
import { Route as AuthenticatedNetworksNetworkIdRouteImport } from './routes/_authenticated/networks/$networkId'
import { Route as AuthenticatedHostsHostIdRouteImport } from './routes/_authenticated/hosts/$hostId'
import { Route as AuthenticatedAlertsAlertIdRouteImport } from './routes/_authenticated/alerts/$alertId'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminSshAlertDefaultsRouteImport } from './routes/_authenticated/admin/ssh-alert-defaults'
import { Route as AuthenticatedAdminRolesRouteImport } from './routes/_authenticated/admin/roles'
import { Route as AuthenticatedAdminOrganizationRouteImport } from './routes/_authenticated/admin/organization'
import { Route as AuthenticatedAdminHostnameLookupRouteImport } from './routes/_authenticated/admin/hostname-lookup'
import { Route as AuthenticatedAdminGvmLibraryRouteImport } from './routes/_authenticated/admin/gvm-library'
import { Route as AuthenticatedNseEditorScriptNameRouteImport } from './routes/_authenticated/nse/editor.$scriptName'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTrendsRoute = AuthenticatedTrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAlertRulesRoute = AuthenticatedAlertRulesRouteImport.update({
  id: '/alert-rules',
  path: '/alert-rules',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedScansIndexRoute = AuthenticatedScansIndexRouteImport.update({
  id: '/scans/',
  path: '/scans/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedScannersIndexRoute =
  AuthenticatedScannersIndexRouteImport.update({
    id: '/scanners/',
    path: '/scanners/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNetworksIndexRoute =
  AuthenticatedNetworksIndexRouteImport.update({
    id: '/networks/',
    path: '/networks/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHostsIndexRoute = AuthenticatedHostsIndexRouteImport.update({
  id: '/hosts/',
  path: '/hosts/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAlertsIndexRoute =
  AuthenticatedAlertsIndexRouteImport.update({
    id: '/alerts/',
    path: '/alerts/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedScansScanIdRoute =
  AuthenticatedScansScanIdRouteImport.update({
    id: '/scans/$scanId',
    path: '/scans/$scanId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedScannersScannerIdRoute =
  AuthenticatedScannersScannerIdRouteImport.update({
    id: '/scanners/$scannerId',
    path: '/scanners/$scannerId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNseResultsRoute = AuthenticatedNseResultsRouteImport.update({
  id: '/nse/results',
  path: '/nse/results',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNseProfilesRoute =
  AuthenticatedNseProfilesRouteImport.update({
    id: '/nse/profiles',
    path: '/nse/profiles',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNseLibraryRoute = AuthenticatedNseLibraryRouteImport.update({
  id: '/nse/library',
  path: '/nse/library',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNetworksNetworkIdRoute =
  AuthenticatedNetworksNetworkIdRouteImport.update({
    id: '/networks/$networkId',
    path: '/networks/$networkId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHostsHostIdRoute =
  AuthenticatedHostsHostIdRouteImport.update({
    id: '/hosts/$hostId',
    path: '/hosts/$hostId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAlertsAlertIdRoute =
  AuthenticatedAlertsAlertIdRouteImport.update({
    id: '/alerts/$alertId',
    path: '/alerts/$alertId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminSshAlertDefaultsRoute =
  AuthenticatedAdminSshAlertDefaultsRouteImport.update({
    id: '/admin/ssh-alert-defaults',
    path: '/admin/ssh-alert-defaults',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminRolesRoute = AuthenticatedAdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminOrganizationRoute =
  AuthenticatedAdminOrganizationRouteImport.update({
    id: '/admin/organization',
    path: '/admin/organization',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminHostnameLookupRoute =
  AuthenticatedAdminHostnameLookupRouteImport.update({
    id: '/admin/hostname-lookup',
    path: '/admin/hostname-lookup',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminGvmLibraryRoute =
  AuthenticatedAdminGvmLibraryRouteImport.update({
    id: '/admin/gvm-library',
    path: '/admin/gvm-library',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNseEditorScriptNameRoute =
  AuthenticatedNseEditorScriptNameRouteImport.update({
    id: '/nse/editor/$scriptName',
    path: '/nse/editor/$scriptName',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/alert-rules': typeof AuthenticatedAlertRulesRoute
  '/trends': typeof AuthenticatedTrendsRoute
  '/admin/gvm-library': typeof AuthenticatedAdminGvmLibraryRoute
  '/admin/hostname-lookup': typeof AuthenticatedAdminHostnameLookupRoute
  '/admin/organization': typeof AuthenticatedAdminOrganizationRoute
  '/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/admin/ssh-alert-defaults': typeof AuthenticatedAdminSshAlertDefaultsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/alerts/$alertId': typeof AuthenticatedAlertsAlertIdRoute
  '/hosts/$hostId': typeof AuthenticatedHostsHostIdRoute
  '/networks/$networkId': typeof AuthenticatedNetworksNetworkIdRoute
  '/nse/library': typeof AuthenticatedNseLibraryRoute
  '/nse/profiles': typeof AuthenticatedNseProfilesRoute
  '/nse/results': typeof AuthenticatedNseResultsRoute
  '/scanners/$scannerId': typeof AuthenticatedScannersScannerIdRoute
  '/scans/$scanId': typeof AuthenticatedScansScanIdRoute
  '/alerts/': typeof AuthenticatedAlertsIndexRoute
  '/hosts/': typeof AuthenticatedHostsIndexRoute
  '/networks/': typeof AuthenticatedNetworksIndexRoute
  '/scanners/': typeof AuthenticatedScannersIndexRoute
  '/scans/': typeof AuthenticatedScansIndexRoute
  '/nse/editor/$scriptName': typeof AuthenticatedNseEditorScriptNameRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/alert-rules': typeof AuthenticatedAlertRulesRoute
  '/trends': typeof AuthenticatedTrendsRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/gvm-library': typeof AuthenticatedAdminGvmLibraryRoute
  '/admin/hostname-lookup': typeof AuthenticatedAdminHostnameLookupRoute
  '/admin/organization': typeof AuthenticatedAdminOrganizationRoute
  '/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/admin/ssh-alert-defaults': typeof AuthenticatedAdminSshAlertDefaultsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/alerts/$alertId': typeof AuthenticatedAlertsAlertIdRoute
  '/hosts/$hostId': typeof AuthenticatedHostsHostIdRoute
  '/networks/$networkId': typeof AuthenticatedNetworksNetworkIdRoute
  '/nse/library': typeof AuthenticatedNseLibraryRoute
  '/nse/profiles': typeof AuthenticatedNseProfilesRoute
  '/nse/results': typeof AuthenticatedNseResultsRoute
  '/scanners/$scannerId': typeof AuthenticatedScannersScannerIdRoute
  '/scans/$scanId': typeof AuthenticatedScansScanIdRoute
  '/alerts': typeof AuthenticatedAlertsIndexRoute
  '/hosts': typeof AuthenticatedHostsIndexRoute
  '/networks': typeof AuthenticatedNetworksIndexRoute
  '/scanners': typeof AuthenticatedScannersIndexRoute
  '/scans': typeof AuthenticatedScansIndexRoute
  '/nse/editor/$scriptName': typeof AuthenticatedNseEditorScriptNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/alert-rules': typeof AuthenticatedAlertRulesRoute
  '/_authenticated/trends': typeof AuthenticatedTrendsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/gvm-library': typeof AuthenticatedAdminGvmLibraryRoute
  '/_authenticated/admin/hostname-lookup': typeof AuthenticatedAdminHostnameLookupRoute
  '/_authenticated/admin/organization': typeof AuthenticatedAdminOrganizationRoute
  '/_authenticated/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/_authenticated/admin/ssh-alert-defaults': typeof AuthenticatedAdminSshAlertDefaultsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/alerts/$alertId': typeof AuthenticatedAlertsAlertIdRoute
  '/_authenticated/hosts/$hostId': typeof AuthenticatedHostsHostIdRoute
  '/_authenticated/networks/$networkId': typeof AuthenticatedNetworksNetworkIdRoute
  '/_authenticated/nse/library': typeof AuthenticatedNseLibraryRoute
  '/_authenticated/nse/profiles': typeof AuthenticatedNseProfilesRoute
  '/_authenticated/nse/results': typeof AuthenticatedNseResultsRoute
  '/_authenticated/scanners/$scannerId': typeof AuthenticatedScannersScannerIdRoute
  '/_authenticated/scans/$scanId': typeof AuthenticatedScansScanIdRoute
  '/_authenticated/alerts/': typeof AuthenticatedAlertsIndexRoute
  '/_authenticated/hosts/': typeof AuthenticatedHostsIndexRoute
  '/_authenticated/networks/': typeof AuthenticatedNetworksIndexRoute
  '/_authenticated/scanners/': typeof AuthenticatedScannersIndexRoute
  '/_authenticated/scans/': typeof AuthenticatedScansIndexRoute
  '/_authenticated/nse/editor/$scriptName': typeof AuthenticatedNseEditorScriptNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/alert-rules'
    | '/trends'
    | '/admin/gvm-library'
    | '/admin/hostname-lookup'
    | '/admin/organization'
    | '/admin/roles'
    | '/admin/ssh-alert-defaults'
    | '/admin/users'
    | '/alerts/$alertId'
    | '/hosts/$hostId'
    | '/networks/$networkId'
    | '/nse/library'
    | '/nse/profiles'
    | '/nse/results'
    | '/scanners/$scannerId'
    | '/scans/$scanId'
    | '/alerts/'
    | '/hosts/'
    | '/networks/'
    | '/scanners/'
    | '/scans/'
    | '/nse/editor/$scriptName'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/alert-rules'
    | '/trends'
    | '/'
    | '/admin/gvm-library'
    | '/admin/hostname-lookup'
    | '/admin/organization'
    | '/admin/roles'
    | '/admin/ssh-alert-defaults'
    | '/admin/users'
    | '/alerts/$alertId'
    | '/hosts/$hostId'
    | '/networks/$networkId'
    | '/nse/library'
    | '/nse/profiles'
    | '/nse/results'
    | '/scanners/$scannerId'
    | '/scans/$scanId'
    | '/alerts'
    | '/hosts'
    | '/networks'
    | '/scanners'
    | '/scans'
    | '/nse/editor/$scriptName'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/alert-rules'
    | '/_authenticated/trends'
    | '/_authenticated/'
    | '/_authenticated/admin/gvm-library'
    | '/_authenticated/admin/hostname-lookup'
    | '/_authenticated/admin/organization'
    | '/_authenticated/admin/roles'
    | '/_authenticated/admin/ssh-alert-defaults'
    | '/_authenticated/admin/users'
    | '/_authenticated/alerts/$alertId'
    | '/_authenticated/hosts/$hostId'
    | '/_authenticated/networks/$networkId'
    | '/_authenticated/nse/library'
    | '/_authenticated/nse/profiles'
    | '/_authenticated/nse/results'
    | '/_authenticated/scanners/$scannerId'
    | '/_authenticated/scans/$scanId'
    | '/_authenticated/alerts/'
    | '/_authenticated/hosts/'
    | '/_authenticated/networks/'
    | '/_authenticated/scanners/'
    | '/_authenticated/scans/'
    | '/_authenticated/nse/editor/$scriptName'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/trends': {
      id: '/_authenticated/trends'
      path: '/trends'
      fullPath: '/trends'
      preLoaderRoute: typeof AuthenticatedTrendsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/alert-rules': {
      id: '/_authenticated/alert-rules'
      path: '/alert-rules'
      fullPath: '/alert-rules'
      preLoaderRoute: typeof AuthenticatedAlertRulesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/scans/': {
      id: '/_authenticated/scans/'
      path: '/scans'
      fullPath: '/scans/'
      preLoaderRoute: typeof AuthenticatedScansIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/scanners/': {
      id: '/_authenticated/scanners/'
      path: '/scanners'
      fullPath: '/scanners/'
      preLoaderRoute: typeof AuthenticatedScannersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/networks/': {
      id: '/_authenticated/networks/'
      path: '/networks'
      fullPath: '/networks/'
      preLoaderRoute: typeof AuthenticatedNetworksIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hosts/': {
      id: '/_authenticated/hosts/'
      path: '/hosts'
      fullPath: '/hosts/'
      preLoaderRoute: typeof AuthenticatedHostsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/alerts/': {
      id: '/_authenticated/alerts/'
      path: '/alerts'
      fullPath: '/alerts/'
      preLoaderRoute: typeof AuthenticatedAlertsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/scans/$scanId': {
      id: '/_authenticated/scans/$scanId'
      path: '/scans/$scanId'
      fullPath: '/scans/$scanId'
      preLoaderRoute: typeof AuthenticatedScansScanIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/scanners/$scannerId': {
      id: '/_authenticated/scanners/$scannerId'
      path: '/scanners/$scannerId'
      fullPath: '/scanners/$scannerId'
      preLoaderRoute: typeof AuthenticatedScannersScannerIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/nse/results': {
      id: '/_authenticated/nse/results'
      path: '/nse/results'
      fullPath: '/nse/results'
      preLoaderRoute: typeof AuthenticatedNseResultsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/nse/profiles': {
      id: '/_authenticated/nse/profiles'
      path: '/nse/profiles'
      fullPath: '/nse/profiles'
      preLoaderRoute: typeof AuthenticatedNseProfilesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/nse/library': {
      id: '/_authenticated/nse/library'
      path: '/nse/library'
      fullPath: '/nse/library'
      preLoaderRoute: typeof AuthenticatedNseLibraryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/networks/$networkId': {
      id: '/_authenticated/networks/$networkId'
      path: '/networks/$networkId'
      fullPath: '/networks/$networkId'
      preLoaderRoute: typeof AuthenticatedNetworksNetworkIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hosts/$hostId': {
      id: '/_authenticated/hosts/$hostId'
      path: '/hosts/$hostId'
      fullPath: '/hosts/$hostId'
      preLoaderRoute: typeof AuthenticatedHostsHostIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/alerts/$alertId': {
      id: '/_authenticated/alerts/$alertId'
      path: '/alerts/$alertId'
      fullPath: '/alerts/$alertId'
      preLoaderRoute: typeof AuthenticatedAlertsAlertIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/ssh-alert-defaults': {
      id: '/_authenticated/admin/ssh-alert-defaults'
      path: '/admin/ssh-alert-defaults'
      fullPath: '/admin/ssh-alert-defaults'
      preLoaderRoute: typeof AuthenticatedAdminSshAlertDefaultsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/roles': {
      id: '/_authenticated/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AuthenticatedAdminRolesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/organization': {
      id: '/_authenticated/admin/organization'
      path: '/admin/organization'
      fullPath: '/admin/organization'
      preLoaderRoute: typeof AuthenticatedAdminOrganizationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/hostname-lookup': {
      id: '/_authenticated/admin/hostname-lookup'
      path: '/admin/hostname-lookup'
      fullPath: '/admin/hostname-lookup'
      preLoaderRoute: typeof AuthenticatedAdminHostnameLookupRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/gvm-library': {
      id: '/_authenticated/admin/gvm-library'
      path: '/admin/gvm-library'
      fullPath: '/admin/gvm-library'
      preLoaderRoute: typeof AuthenticatedAdminGvmLibraryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/nse/editor/$scriptName': {
      id: '/_authenticated/nse/editor/$scriptName'
      path: '/nse/editor/$scriptName'
      fullPath: '/nse/editor/$scriptName'
      preLoaderRoute: typeof AuthenticatedNseEditorScriptNameRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAlertRulesRoute: typeof AuthenticatedAlertRulesRoute
  AuthenticatedTrendsRoute: typeof AuthenticatedTrendsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAdminGvmLibraryRoute: typeof AuthenticatedAdminGvmLibraryRoute
  AuthenticatedAdminHostnameLookupRoute: typeof AuthenticatedAdminHostnameLookupRoute
  AuthenticatedAdminOrganizationRoute: typeof AuthenticatedAdminOrganizationRoute
  AuthenticatedAdminRolesRoute: typeof AuthenticatedAdminRolesRoute
  AuthenticatedAdminSshAlertDefaultsRoute: typeof AuthenticatedAdminSshAlertDefaultsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAlertsAlertIdRoute: typeof AuthenticatedAlertsAlertIdRoute
  AuthenticatedHostsHostIdRoute: typeof AuthenticatedHostsHostIdRoute
  AuthenticatedNetworksNetworkIdRoute: typeof AuthenticatedNetworksNetworkIdRoute
  AuthenticatedNseLibraryRoute: typeof AuthenticatedNseLibraryRoute
  AuthenticatedNseProfilesRoute: typeof AuthenticatedNseProfilesRoute
  AuthenticatedNseResultsRoute: typeof AuthenticatedNseResultsRoute
  AuthenticatedScannersScannerIdRoute: typeof AuthenticatedScannersScannerIdRoute
  AuthenticatedScansScanIdRoute: typeof AuthenticatedScansScanIdRoute
  AuthenticatedAlertsIndexRoute: typeof AuthenticatedAlertsIndexRoute
  AuthenticatedHostsIndexRoute: typeof AuthenticatedHostsIndexRoute
  AuthenticatedNetworksIndexRoute: typeof AuthenticatedNetworksIndexRoute
  AuthenticatedScannersIndexRoute: typeof AuthenticatedScannersIndexRoute
  AuthenticatedScansIndexRoute: typeof AuthenticatedScansIndexRoute
  AuthenticatedNseEditorScriptNameRoute: typeof AuthenticatedNseEditorScriptNameRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAlertRulesRoute: AuthenticatedAlertRulesRoute,
  AuthenticatedTrendsRoute: AuthenticatedTrendsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAdminGvmLibraryRoute: AuthenticatedAdminGvmLibraryRoute,
  AuthenticatedAdminHostnameLookupRoute: AuthenticatedAdminHostnameLookupRoute,
  AuthenticatedAdminOrganizationRoute: AuthenticatedAdminOrganizationRoute,
  AuthenticatedAdminRolesRoute: AuthenticatedAdminRolesRoute,
  AuthenticatedAdminSshAlertDefaultsRoute:
    AuthenticatedAdminSshAlertDefaultsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAlertsAlertIdRoute: AuthenticatedAlertsAlertIdRoute,
  AuthenticatedHostsHostIdRoute: AuthenticatedHostsHostIdRoute,
  AuthenticatedNetworksNetworkIdRoute: AuthenticatedNetworksNetworkIdRoute,
  AuthenticatedNseLibraryRoute: AuthenticatedNseLibraryRoute,
  AuthenticatedNseProfilesRoute: AuthenticatedNseProfilesRoute,
  AuthenticatedNseResultsRoute: AuthenticatedNseResultsRoute,
  AuthenticatedScannersScannerIdRoute: AuthenticatedScannersScannerIdRoute,
  AuthenticatedScansScanIdRoute: AuthenticatedScansScanIdRoute,
  AuthenticatedAlertsIndexRoute: AuthenticatedAlertsIndexRoute,
  AuthenticatedHostsIndexRoute: AuthenticatedHostsIndexRoute,
  AuthenticatedNetworksIndexRoute: AuthenticatedNetworksIndexRoute,
  AuthenticatedScannersIndexRoute: AuthenticatedScannersIndexRoute,
  AuthenticatedScansIndexRoute: AuthenticatedScansIndexRoute,
  AuthenticatedNseEditorScriptNameRoute: AuthenticatedNseEditorScriptNameRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
